#!/bin/sh
 
PROJECT_NAME=SoloWeb29
PROJECT_TYPE=framework
DESTINATION_DIRECTORY=/Library/Frameworks/
OLD_APP_NAME=x$PROJECT_NAME`date "+_%Y_%m_%d_%H_%M_%S"`.$PROJECT_TYPE

mv $DESTINATION_DIRECTORY$PROJECT_NAME.$PROJECT_TYPE $DESTINATION_DIRECTORY$OLD_APP_NAME

cp -R $PROJECT_NAME/dist/$PROJECT_NAME.$PROJECT_TYPE $DESTINATION_DIRECTORY